M48
; DRILL file KiCad 10.0.5 date 2026-07-26T12:52:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-26T12:52:16-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X28.787Y-34.5
X29.0Y-82.0
X138.5Y-34.5
X138.713Y-82.0
M30
